import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-gray-800 text-white p-4">
          <div className="max-w-2xl mx-auto flex gap-4">
            <a href="/" className="hover:text-gray-300">
              Home
            </a>
            <a href="/blog" className="hover:text-gray-300">
              Blog
            </a>
            <a href="/about" className="hover:text-gray-300">
              About
            </a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
